version: 2

orbs:
  slack: circleci/slack@3.4.0

jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
          
      - slack/notify:
          color: '#42e2f4'
          message: This is a custom message notification ${CIRCLE_USERNAME}
