version: 2.1

orbs:
  slack: circleci/slack@3.4.0

parameters:
  slack_user:
    type: string
    default: "U0E4MF1NV"
  slack_channel:
    type: string
    default: "#general"
    
jobs:
  build:
    parallelism: 3
    docker:
      - image: circleci/node:7.10

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
workflows:
  test_slack:
    jobs:
      - build:
          post-steps:
            - slack/status:
                mentions: << pipeline.parameters.slack_user >>
                channel: << pipeline.parameters.slack_channel >>
                include_job_number_field: false
                include_project_field: false
                success_message: ":tada:${CIRCLE_BRANCH}のテストが成功したよ！( ^ヮ^)\n${CIRCLE_PULL_REQUEST}"
                failure_message: ":x:${CIRCLE_BRANCH}テストが失敗しちゃったよ( x_x)\n${CIRCLE_PULL_REQUEST}"
