version: 2.1

orbs:
  slack: circleci/slack@3.4.0

parameters:
  slack_name:
    type: string
    default: "rockwjx"
  slack_channel:
    type: string
    default: ""
    
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
          
      - slack/notify:
          color: '#42e2f4'
          mentions: << pipeline.parameters.slack_name >>
          message: "This is a custom message notification!!!"
          title: "ブランチ： ${CIRCLE_BRANCH}"
          title_link: ${CIRCLE_PULL_REQUEST}
          channel: "#general"
