version: 2.1

orbs:
  slack: circleci/slack@3.4.0

parameters:
  slack_name:
    type: string
    default: ""
  slack_channel:
    type: string
    default: "U0E4MF1NV"
    
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
          
      - slack/status:
          mentions: << pipeline.parameters.slack_name >>
          channel: "#general"
