version: 2.1

orbs:
  slack: circleci/slack@3.4.0

workflows:
  test-slack-notify:
    jobs:
      - test-slack-notify
          
jobs:
  test-slack-notify:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    steps:
      - checkout
      - run:
        command: echo "Hello ${CIRCLE_USERNAME}"
      - slack/notify:
          color: '#42e2f4'
          message: This is a custom message notification ${CIRCLE_USERNAME}
