version: 2.1

orbs:
  slack: circleci/slack@3.4.0

jobs:
  build:
    docker:
      - image: circleci/node:7.10

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
          
      - slack/notify:
          color: '#42e2f4'
          message: "This is a custom message notification <@rockwjx>"
          channel: "#general"
